name: Angular Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Build Angular app to prod
        working-directory: infra-automation-app
        run: npm install && npm run build:prod 

      - name: Deploy to GitHub Pages
        uses: yashtank09/infra-automation@v4
        with:
          folder: infra-automation-app/dist/browser
          branch: prod  
          token: ${{ secrets.TEST_SECRETS }}